apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: order-service
  name: order-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: order-service
    spec:
      containers:
        - image: thanhvv/icommerce-order-service
          name: order-service
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: web-server
spec:
  selector:
    app: web-server
  ports:
    - port: 4200
      targetPort: 80
  type: LoadBalancer
